covidStats/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('statsApp.urls')),
    path('admin/', admin.site.urls),
]

statsApp/urls.py
from django.urls import path

from . import views

app_name = 'statsApp'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.CountryView.as_view(), name='country')
]

statsApp/models.py
from django.db import models


# Create your models here.
class Stats(models.Model):
    country = models.CharField(max_length=200)
    country_iso = models.CharField(max_length=3)
    lat = models.FloatField(null=True)
    lang = models.FloatField(null=True)
    flag = models.CharField(max_length=200)
    cases = models.IntegerField(null=True)
    todayCases = models.IntegerField(null=True)
    deaths = models.IntegerField(null=True)
    todayDeaths = models.IntegerField(null=True)
    recovered = models.IntegerField(null=True)
    todayRecovered = models.IntegerField(null=True)
    active = models.IntegerField(null=True)
    critical = models.IntegerField(null=True)
    casesPerOneMillion = models.IntegerField(null=True)
    deathsPerOneMillion = models.IntegerField(null=True)
    tests = models.IntegerField(null=True)
    testsPerOneMillion = models.IntegerField(null=True)
    population = models.IntegerField(null=True)
    continent = models.CharField(max_length=200)
    oneCasePerPeople = models.IntegerField(null=True)
    oneDeathPerPeople = models.IntegerField(null=True)
    oneTestPerPeople = models.IntegerField(null=True)
    activePerOneMillion = models.FloatField(null=True)
    recoveredPerOneMillion = models.FloatField(null=True)
    criticalPerOneMillion = models.FloatField(null=True)

    def __str__(self):
        return self.country

statsApp/views.py
from django.http import HttpResponse
from django.shortcuts import render
import json
# Create your views here.
from django.views import generic

from .models import Stats


def index(request):
    return HttpResponse("Hello from stats app.")


class IndexView(generic.ListView):
    template_name = 'statsApp/index.html'
    context_object_name = 'country_stats_list'

    def get_queryset(self):
        return Stats.objects.order_by('-cases')

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        country_names = Stats.objects.values_list('country', flat=True).order_by('-cases')[:10]
        country_cases = Stats.objects.values_list('cases', flat=True).order_by('-cases')[:10]
        country_active = Stats.objects.values_list('active', flat=True).order_by('-cases')[:10]
        country_recovered = Stats.objects.values_list('recovered', flat=True).order_by('-cases')[:10]
        country_deaths = Stats.objects.values_list('deaths', flat=True).order_by('-cases')[:10]
        country_critical = Stats.objects.values_list('critical', flat=True).order_by('-cases')[:10]
        country_names = list(country_names)
        country_cases = list(country_cases)
        country_active = list(country_active)
        country_recovered = list(country_recovered)
        country_deaths = list(country_deaths)
        country_critical = list(country_critical)
        print(country_active)
        print(country_recovered)
        context['country_name_list'] = country_names
        context['country_case_list'] = country_cases
        context['country_active_list'] = country_active
        context['country_recovered_list'] = country_recovered
        context['country_deaths_list'] = country_deaths
        context['country_critical_list'] = country_critical
        return context


class CountryView(generic.DetailView):
    model = Stats
    template_name = 'statsApp/country.html'
    context_object_name = 'country'

    def get_context_data(self, **kwargs):
        context = super(CountryView, self).get_context_data(**kwargs)
        for key, value in context.items():
            country_stat = value
        print(context.items())
        return context

statsApp/templates/statsApp/base.html
<html>
<head>
    <title>Covid Stats App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.3/css/bootstrap.min.css" integrity="sha512-oc9+XSs1H243/FRN9Rw62Fn8EtxjEYWHXRvjS43YtueEewbS6ObfXcJNyohjHqVKFPoXXUxwc+q1K7Dee6vv9g==" crossorigin="anonymous" />
    {% load static %}
    <link rel="icon" href="{% static 'statsApp/images/logo.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'statsApp/styles.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    <script src="{% static 'statsApp/app.js' %}"></script>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark justify-content-start">
        <a class="navbar-brand mr-3" href="/">
            <img src="{% static 'statsApp/images/logo.png' %}" width="30" height="30" alt="" loading="lazy">
            <span class="mt-2 ml-2">COVID STATS</span>
        </a>
        <a class="nav-item btn btn-secondary ml-3" href="/">
            Home
        </a>
    </nav>

    <div class="container main mt-3">
        {% block content %}
        {% endblock content %}
    </div>

<footer class="navbar navbar-dark bg-dark mt-3 pt-3">
  <div class="container d-flex justify-content-between align-items-center">
      <span class="text-muted float-right"><em>&copy;Rights Reserved</em></span>
      <span class="text-muted float-right"><em>Developed by - <strong>Vishal Vasishat&reg;</strong></em></span>
  </div>
</footer>
</body>
</html>

statsApp/templates/statsApp/country.html
{% extends 'statsApp/base.html' %}

{% block content %}
      <div class="country-wrapper">
            <div class="row">
                  <div class="col-sm-5">
                        <div>
                              <h1>{{country}}</h1>
                        </div>
                         <img src="{{country.flag}}" height="100" />
                         <ul class="list-group mt-3">
                             <li class="list-group-item list-group-item-secondary d-flex justify-content-between align-items-center">
                                 <strong>Total Cases </strong>
                                 <span class="badge badge-secondary badge-pill">{{country.cases}}</span>
                             </li>
                             <li class="list-group-item list-group-item-primary d-flex justify-content-between align-items-center">
                                  Active Cases
                                 <span class="badge badge-primary badge-pill">{{country.active}}</span>
                             </li>
                             <li class="list-group-item list-group-item-success d-flex justify-content-between align-items-center">
                                 Recovered Cases
                                 <span class="badge badge-success badge-pill">{{country.recovered}}</span>
                             </li>
                             <li class="list-group-item list-group-item-danger d-flex justify-content-between align-items-center">
                                  Total Deaths
                                  <span class="badge badge-danger badge-pill">{{country.deaths}}</span>
                             </li>
                             <li class="list-group-item list-group-item-warning d-flex justify-content-between align-items-center">
                                  Critical Cases
                                  <span class="badge badge-warning badge-pill">{{country.critical}}</span>
                             </li>
                         </ul>
                  </div>
                  <div class="col-sm-5">
                        <canvas id="countryChart" width="400" height="400"></canvas>
                  </div>
            </div>
      </div>

    <script>
         var ctx = document.getElementById('countryChart').getContext('2d');
         loadCountryPieData({{country.active}}, {{country.recovered}}, {{country.deaths}}, {{country.critical}})
    </script>
{% endblock content %}

statsApp/templates/statsApp/index.html
{% extends 'statsApp/base.html' %}

{% block content %}
    {% if country_stats_list %}
    <div class="row">
        <div class="col-sm-5">
            <div class="form-group col-sm-10">
                <label for="country"><strong>Select Country</strong></label>
                <select class="form-control" id="country" ONCHANGE="location = this.selectedIndex !== 0 ? this.options[this.selectedIndex].value : '/';">
                  <option selected>Top Ten</option>
                    {% for country in country_stats_list %}
                    <option value="{% url 'statsApp:country' country.id %}">
                       {{country.country}}
                    </option>
                    {% endfor %}
                </select>
              </div>
        </div>
        <canvas id="myChart" width="400" height="400" class="col-sm-6"></canvas>
    </div>
    {% else %}
            <h2 class="text-danger">No data available.</h2>
    {% endif %}

    <script>
         var ctx = document.getElementById('myChart').getContext('2d');
         loadChartData({{country_name_list | safe}}, {{country_case_list}}, {{country_active_list}}, {{country_recovered_list}}, {{country_deaths_list}}, {{country_critical_list}})
    </script>
{% endblock content %}